package ${serviceUrl};

import ${entityUrl}.${entityName};
import com.baomidou.mybatisplus.extension.service.IService;
/**
* generated by mybatis-generator
*/
public interface ${entityName}Service extends IService<${entityName}> {
	
}